
[minecraft]
	replace_dolphin = true
	replace_bee = false
	replace_wolf = true
	replace_ocelot = true
	replace_fox = true
	replace_cat = true
	replace_mooshroom = true
	replace_silverfish = true
	replace_squid = true
	replace_polarbear = true
	replace_spider = true
	replace_sheep = true
	replace_cavespider = true
	replace_cow = true
	replace_pig = true
	replace_chicken = true

[quark_compat]
	#enable overriding quark's override. Cow must be enabled as well.
	enablequarkoverridecow = true
	#enable overriding quark's override. Pig must be enabled as well.
	enablequarkoverridepig = true
	#enable overriding quark's override. Chicken must be enabled as well.
	enablequarkoverridechicken = true
	#enable overriding quark's override. Bee must be enabled as well. This will not have the LGBT bee textures, as there are too many for us to make right now.
	enablequarkoverridebee = false

